import { ScriptureTSV } from "../core/TsvTypes"

export const titusTsvs: ScriptureTSV = {
  1: {
    1: [
      {
        Reference: '1:1',
        ID: 'h5gl',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: '',
        Occurrence: '0',
        Note: 'Though this letter is from Paul and Timothy to the Colossian believers, later in the letter Paul makes it clear that he is the writer. Most likely Timothy was with him and wrote the words down as Paul spoke. Throughout this letter the words “we,” “our,” and “ours” include the Colossians unless noted otherwise. The words “you,” “your,” and “yours” refer to the Colossian believers and so are plural unless noted otherwise. (See: [[rc://*/ta/man/translate/figs-exclusive]] and [[rc://*/ta/man/translate/figs-you]])',
      },
      {
        Reference: '1:1',
        ID: 'fny3',
        Tags: '',
        SupportReference: '',
        Quote: 'ἀπόστολος Χριστοῦ Ἰησοῦ διὰ θελήματος Θεοῦ',
        Occurrence: '1',
        Note: '“whom God chose to be an apostle of Christ Jesus”',
      },
    ],
    3: [
      {
        Reference: '1:3',
        ID: 'q1su',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: 'εὐχαριστοῦμεν & τοῦ Κυρίου ἡμῶν & πάντοτε',
        Occurrence: '1',
        Note: 'These words do not include the Colossians. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
    ],
    4: [
      {
        Reference: '1:4',
        ID: 'km8w',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: 'ἀκούσαντες',
        Occurrence: '1',
        Note: 'Paul is excluding his audience. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
      {
        Reference: '1:4',
        ID: 'z6eb',
        Tags: '',
        SupportReference: '',
        Quote: 'τὴν πίστιν ὑμῶν ἐν Χριστῷ Ἰησοῦ',
        Occurrence: '1',
        Note: '“your belief in Christ Jesus”',
      },
    ],
    5: [
      {
        Reference: '1:5',
        ID: 'n1qz',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'διὰ τὴν ἐλπίδα τὴν ἀποκειμένην ὑμῖν ἐν τοῖς οὐρανοῖς',
        Occurrence: '1',
        Note: 'Here “certain hope” stands for what the believer can confidently expect, that is, the things that God has promised to do for all believers. These things are spoken of as if they were physical objects that God was keeping in heaven for the believers to possess later. Alternate translation: “because you are certain that God, who is in heaven, will do the many good things that he has promised you” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
      {
        Reference: '1:5',
        ID: 'xn8s',
        Tags: '',
        SupportReference: '',
        Quote: 'τῷ λόγῳ τῆς ἀληθείας, τοῦ εὐαγγελίου',
        Occurrence: '1',
        Note: 'Possible meanings are (1) “the message about the truth, the gospel” or (2) “the true message, the gospel.”',
      },
    ],
    6: [
      {
        Reference: '1:6',
        ID: 'wk21',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐστὶν καρποφορούμενον καὶ αὐξανόμενον',
        Occurrence: '1',
        Note: '“Fruit” here is a metaphor for “result” or “outcome.” Alternate translation: “This gospel is having good results, more and more” or “This gospel is having increasing results” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:6',
        ID: 'z3g5',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-hyperbole',
        Quote: 'ἐν παντὶ τῷ κόσμῳ',
        Occurrence: '1',
        Note: 'This is a generalization referring to the part of the world that they knew about. Alternate translation: “throughout the world” (See: [[rc://*/ta/man/translate/figs-hyperbole]])',
      },
      {
        Reference: '1:6',
        ID: 'ait7',
        Tags: '',
        SupportReference: '',
        Quote: 'τὴν χάριν τοῦ Θεοῦ ἐν ἀληθείᾳ',
        Occurrence: '1',
        Note: '“the true grace of God”',
      },
    ],
    7: [
      {
        Reference: '1:7',
        ID: 'f8t1',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: 'ἡμῶν & ἡμῶν',
        Occurrence: '1',
        Note: 'The word “our” does not include the Colossians. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
      {
        Reference: '1:7',
        ID: 'mjv5',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐμάθετε ἀπὸ Ἐπαφρᾶ, τοῦ ἀγαπητοῦ συνδούλου ἡμῶν, ὅς',
        Occurrence: '1',
        Note: '“gospel. It is exactly what you learned from Epaphras, who is our beloved fellow servant and who” or “gospel. It is exactly what Epaphras, our beloved fellow servant, taught you. He”',
      },
      {
        Reference: '1:7',
        ID: 'q8gt',
        Tags: '',
        SupportReference: '',
        Quote:
          'Ἐπαφρᾶ, τοῦ ἀγαπητοῦ συνδούλου ἡμῶν, ὅς ἐστιν πιστὸς ὑπὲρ ἡμῶν διάκονος τοῦ Χριστοῦ',
        Occurrence: '1',
        Note: 'Here “on our behalf” means that Epaphras was doing work for Christ that Paul himself would have done if he were not in prison.',
      },
      {
        Reference: '1:7',
        ID: 'pz3h',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/translate-names',
        Quote: 'Ἐπαφρᾶ',
        Occurrence: '1',
        Note: 'the man who preached the gospel to the people in Colossae (See: [[rc://*/ta/man/translate/translate-names]])',
      },
    ],
    8: [
      {
        Reference: '1:8',
        ID: 'k2k9',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: 'ἡμῖν',
        Occurrence: '1',
        Note: 'The word “us” does not include the Colossians. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
      {
        Reference: '1:8',
        ID: 'e7ez',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'τὴν ὑμῶν ἀγάπην ἐν Πνεύματι',
        Occurrence: '1',
        Note: 'Paul speaks of the Holy Spirit as if he were a place in which the believers were located. Alternate translation: “how the Holy Spirit has enabled you to love believers” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    9: [
      {
        Reference: '1:9',
        ID: 'iyq4',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Because the Spirit has enabled them to love others, Paul prays for them and tells them here how he prays for them.',
      },
      {
        Reference: '1:9',
        ID: 's83e',
        Tags: '',
        SupportReference: '',
        Quote: 'διὰ τοῦτο',
        Occurrence: '1',
        Note: '“Because the Holy Spirit has enabled you to love other believers”',
      },
      {
        Reference: '1:9',
        ID: 'f2xd',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: 'ἡμεῖς & ἠκούσαμεν & καὶ αἰτούμενοι',
        Occurrence: '1',
        Note: 'The word “we” does not include the Colossians. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
      {
        Reference: '1:9',
        ID: 'u7zh',
        Tags: '',
        SupportReference: '',
        Quote: 'ἀφ’ ἧς ἡμέρας ἠκούσαμεν',
        Occurrence: '1',
        Note: '“from the day Epaphras told us these things”',
      },
      {
        Reference: '1:9',
        ID: 'w2a7',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἵνα πληρωθῆτε τὴν ἐπίγνωσιν τοῦ θελήματος αὐτοῦ',
        Occurrence: '1',
        Note: 'Paul speaks of the Colossian believers as though they were containers. Alternate translation: “that God will fill you with what you need to know so that you can do his will” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:9',
        ID: 'mzz8',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐν πάσῃ σοφίᾳ καὶ συνέσει πνευματικῇ',
        Occurrence: '1',
        Note: '“, so that the Holy Spirit will make you wise and able to understand what God wants you to do”',
      },
    ],
    10: [
      {
        Reference: '1:10',
        ID: 'cz4a',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: 'περιπατῆσαι',
        Occurrence: '1',
        Note: 'The word “we” does not include the Colossians. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
      {
        Reference: '1:10',
        ID: 'm4hf',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'περιπατῆσαι ἀξίως τοῦ Κυρίου',
        Occurrence: '1',
        Note: 'Walking here signifies behavior in life. Alternate translation: “We have been praying that you will live the way God expects you to” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:10',
        ID: 'vv4g',
        Tags: '',
        SupportReference: '',
        Quote: 'εἰς πᾶσαν ἀρεσκείαν',
        Occurrence: '1',
        Note: '“in ways that will please the Lord”',
      },
      {
        Reference: '1:10',
        ID: 'vfp3',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'καρποφοροῦντες',
        Occurrence: '1',
        Note: 'Paul is speaking of the Colossian believers as if they were trees or plants. As a plant grows and bears fruit, so also believers are to keep getting to know God better and doing good deeds. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    11: [
      {
        Reference: '1:11',
        ID: 'gxv6',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: 'δυναμούμενοι',
        Occurrence: '1',
        Note: 'The word “we” refers to Paul and Timothy but not to the Colossians. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
      {
        Reference: '1:11',
        ID: 'mzf2',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'εἰς πᾶσαν ὑπομονὴν καὶ μακροθυμίαν',
        Occurrence: '1',
        Note: 'Paul speaks of the Colossian believers as if God would move them into a location of perseverance and patience. In reality, he is praying that they will never stop trusting in God and that they will be completely patient as they honor him. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    12: [
      {
        Reference: '1:12',
        ID: 't5lw',
        Tags: '',
        SupportReference: '',
        Quote: 'ἱκανώσαντι ὑμᾶς εἰς τὴν μερίδα',
        Occurrence: '1',
        Note: '“has allowed you to share”',
      },
      {
        Reference: '1:12',
        ID: 'lt2q',
        Tags: '',
        SupportReference: '',
        Quote: 'ἱκανώσαντι ὑμᾶς',
        Occurrence: '1',
        Note: 'Here Paul is focusing on his readers as receivers of God’s blessings. But he does not mean that he himself has no share in those blessings.',
      },
      {
        Reference: '1:12',
        ID: 'r2zw',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'τοῦ κλήρου',
        Occurrence: '1',
        Note: 'Receiving what God has promised believers is spoken of as if it were inheriting property and wealth from a family member. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:12',
        ID: 'hkf5',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐν τῷ φωτί',
        Occurrence: '1',
        Note: 'This idea is opposite to the idea of the dominion of darkness in the next verse. Alternate translation: “in the glory of his presence” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    13: [
      {
        Reference: '1:13',
        ID: 'g9d3',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul talks about the ways in which Christ is excellent.',
      },
      {
        Reference: '1:13',
        ID: 'mv87',
        Tags: '',
        SupportReference: '',
        Quote: 'ὃς ἐρρύσατο ἡμᾶς',
        Occurrence: '1',
        Note: '“God has rescued us”',
      },
      {
        Reference: '1:13',
        ID: 'dw5k',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'τῆς ἐξουσίας τοῦ σκότους',
        Occurrence: '1',
        Note: '“Darkness” here is a metaphor for evil. Alternate translation: “the evil forces that controlled us” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:13',
        ID: 'zav6',
        Tags: '',
        SupportReference:
          'rc://*/ta/man/translate/guidelines-sonofgodprinciples',
        Quote: 'τοῦ Υἱοῦ τῆς ἀγάπης αὐτοῦ',
        Occurrence: '1',
        Note: '“Son” is an important title for Jesus, the Son of God. (See: [[rc://*/ta/man/translate/guidelines-sonofgodprinciples]])',
      },
    ],
    14: [
      {
        Reference: '1:14',
        ID: 'wh6q',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐν ᾧ',
        Occurrence: '1',
        Note: 'Paul often speaks as if the believers were “in” Jesus Christ or “in” God. This can be translated as the beginning of a new sentence. Alternate translation: “by means of whom” or “By means of his Son” or “Because of his Son” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:14',
        ID: 'v5d8',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-abstractnouns',
        Quote: 'ἔχομεν τὴν ἀπολύτρωσιν, τὴν ἄφεσιν τῶν ἁμαρτιῶν',
        Occurrence: '1',
        Note: 'The nouns “redemption” and “forgiveness” can be translated as verbs. Alternate translation: “we are redeemed; our sins are forgiven” or “God redeems us; he forgives our sins” (See: [[rc://*/ta/man/translate/figs-abstractnouns]])',
      },
    ],
    15: [
      {
        Reference: '1:15',
        ID: 'j5u9',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὅς ἐστιν εἰκὼν τοῦ Θεοῦ τοῦ ἀοράτου',
        Occurrence: '1',
        Note: '“His Son is the image of the invisible God.” Here “image” does not mean a representation of something that is visible. Instead, “image” here means that by knowing the Son, we learn what God the Father is like. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:15',
        ID: 'h945',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'πρωτότοκος πάσης κτίσεως',
        Occurrence: '1',
        Note: 'The expression “firstborn” does not refer to when Jesus was born. Instead, it refers to his position as the eternal Son of God the Father. In this sense, “firstborn” is a metaphor meaning “most important.” Jesus is the most important and the unique Son of God. Alternate Translation: “God’s Son, the most important one over all creation” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:15',
        ID: 'af6b',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-abstractnouns',
        Quote: 'πάσης κτίσεως',
        Occurrence: '1',
        Note: 'The noun “creation” can be translated with a verb. Alternate Translation: “all that God created” (See: [[rc://*/ta/man/translate/figs-abstractnouns]])',
      },
    ],
    16: [
      {
        Reference: '1:16',
        ID: 'kru3',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'ὅτι ἐν αὐτῷ ἐκτίσθη τὰ πάντα',
        Occurrence: '1',
        Note: 'This can be stated in active form. Alternate translation: “For by him God created all things” or “God caused the Son to create all things” (See: [[rc://*/ta/man/translate/figs-activepassive]])',
      },
      {
        Reference: '1:16',
        ID: 'zl7j',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'τὰ πάντα δι’ αὐτοῦ καὶ εἰς αὐτὸν ἔκτισται',
        Occurrence: '1',
        Note: 'This can be stated in active form. God caused the Son to create all things for the Son’s glory. Alternate translation: “For by him and for him God created all things” or “God caused him to create all things for himself” (See: [[rc://*/ta/man/translate/figs-activepassive]])',
      },
    ],
    17: [
      {
        Reference: '1:17',
        ID: 'wk9y',
        Tags: '',
        SupportReference: '',
        Quote: 'αὐτός ἐστιν πρὸ πάντων',
        Occurrence: '1',
        Note: '“It is he who existed before all things”',
      },
      {
        Reference: '1:17',
        ID: 'm4lp',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'τὰ πάντα ἐν αὐτῷ συνέστηκεν',
        Occurrence: '1',
        Note: 'Paul is speaking here of the Son controlling all things as if he were physically holding them together. “he holds everything together” (See: [[rc://*/ta/man/translate/figs-activepassive]] and [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    18: [
      {
        Reference: '1:18',
        ID: 'qsf3',
        Tags: '',
        SupportReference: '',
        Quote: 'αὐτός ἐστιν ἡ κεφαλὴ',
        Occurrence: '1',
        Note: '“Jesus Christ, the Son of God, is the head”',
      },
      {
        Reference: '1:18',
        ID: 'q8i3',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'αὐτός ἐστιν ἡ κεφαλὴ τοῦ σώματος, τῆς ἐκκλησίας',
        Occurrence: '1',
        Note: 'Paul speaks of Jesus’ position over the church as if he were the head on the human body. As the head rules the body, so does Jesus rule the church. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:18',
        ID: 'j6uq',
        Tags: '',
        SupportReference: '',
        Quote: 'ἡ ἀρχή',
        Occurrence: '1',
        Note: '“the originating authority.” He is the first chief or founder.',
      },
      {
        Reference: '1:18',
        ID: 's12x',
        Tags: '',
        SupportReference: '',
        Quote: 'πρωτότοκος ἐκ τῶν νεκρῶν',
        Occurrence: '1',
        Note: 'Jesus is the first person to die and come back to life, never to die again.',
      },
    ],
    20: [
      {
        Reference: '1:20',
        ID: 'as3p',
        Tags: '',
        SupportReference: '',
        Quote: 'διὰ τοῦ αἵματος τοῦ σταυροῦ αὐτοῦ',
        Occurrence: '1',
        Note: '“by means of the blood Jesus shed on the cross”',
      },
      {
        Reference: '1:20',
        ID: 'x5av',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'τοῦ αἵματος τοῦ σταυροῦ αὐτοῦ',
        Occurrence: '1',
        Note: 'Here “blood” stands for the death of Christ on the cross. (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    21: [
      {
        Reference: '1:21',
        ID: 'kv5u',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul makes it clear that God has now revealed that Christ exchanges the sin of Gentile believers for his holiness.',
      },
      {
        Reference: '1:21',
        ID: 'imq1',
        Tags: '',
        SupportReference: '',
        Quote: 'καὶ ὑμᾶς ποτε',
        Occurrence: '1',
        Note: '“There was a time when you Colossian believers also”',
      },
      {
        Reference: '1:21',
        ID: 'wp3t',
        Tags: '',
        SupportReference: '',
        Quote: 'ἀπηλλοτριωμένους',
        Occurrence: '1',
        Note: '“were like people whom God did not know” or “had pushed God away”',
      },
    ],
    22: [
      {
        Reference: '1:22',
        ID: 'ejt4',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote:
          'παραστῆσαι ὑμᾶς ἁγίους, καὶ ἀμώμους, καὶ ἀνεγκλήτους, κατενώπιον αὐτοῦ',
        Occurrence: '1',
        Note: 'Paul is describing the Colossians as though Jesus had physically cleaned them, put them in clean clothes, and brought them to stand before God the Father. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:22',
        ID: 'u94j',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-parallelism',
        Quote: 'ἀμώμους, καὶ ἀνεγκλήτους',
        Occurrence: '1',
        Note: 'Paul uses two words that mean almost the same thing to emphasize the idea of perfection. Alternate translation: “perfect” (See: [[rc://*/ta/man/translate/figs-parallelism]])',
      },
      {
        Reference: '1:22',
        ID: 'lf5a',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'κατενώπιον αὐτοῦ',
        Occurrence: '1',
        Note: 'This expression of location stands for “in God’s view” or “in God’s mind” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    23: [
      {
        Reference: '1:23',
        ID: 'd9kg',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'τοῦ κηρυχθέντος',
        Occurrence: '1',
        Note: 'that believers proclaimed (See: [[rc://*/ta/man/translate/figs-activepassive]])',
      },
      {
        Reference: '1:23',
        ID: 'q21b',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐν πάσῃ κτίσει τῇ ὑπὸ τὸν οὐρανόν',
        Occurrence: '1',
        Note: '“to every person in the world”',
      },
      {
        Reference: '1:23',
        ID: 'g8iq',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'οὗ ἐγενόμην ἐγὼ Παῦλος διάκονος',
        Occurrence: '1',
        Note: 'Paul was actually a servant of God. Alternate translation: “the gospel that I, Paul, serve God by proclaiming” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    24: [
      {
        Reference: '1:24',
        ID: 'rcw3',
        Tags: '',
        SupportReference: '',
        Quote:
          'ἀνταναπληρῶ τὰ ὑστερήματα τῶν θλίψεων τοῦ Χριστοῦ ἐν τῇ σαρκί μου',
        Occurrence: '1',
        Note: 'Paul speaks about the suffering that he continues to experience. He may be acknowledging here that there is much suffering that he and all other Christians must endure before Christ comes again, and that Christ in a spiritual sense joins with them in experiencing these hardships. Paul certainly does not mean that Christ’s sufferings alone were not enough to provide salvation for the believers.',
      },
      {
        Reference: '1:24',
        ID: 'fm9y',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἀνταναπληρῶ & ἐν τῇ σαρκί μου',
        Occurrence: '1',
        Note: 'Paul speaks of his body as if it were a container that could hold suffering. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:24',
        ID: 'mge9',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὑπὲρ τοῦ σώματος αὐτοῦ, ὅ ἐστιν ἡ ἐκκλησία',
        Occurrence: '1',
        Note: 'Paul often speaks of the church, the group of all Christian believers, as if it were Christ’s body. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    25: [
      {
        Reference: '1:25',
        ID: 't6ud',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'πληρῶσαι τὸν λόγον τοῦ Θεοῦ',
        Occurrence: '1',
        Note: 'This means to bring about the purpose of God’s gospel message, which is that it be preached and believed. “Word of God” here is a metonym for the message from God. Alternate translation: “to be obedient to what God has instructed” (See: [[rc://*/ta/man/translate/figs-metaphor]] and [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    26: [
      {
        Reference: '1:26',
        ID: 'f3mt',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'τὸ μυστήριον τὸ ἀποκεκρυμμένον',
        Occurrence: '1',
        Note: 'This can be stated in active form. Alternate translation: “This is the secret truth that God had hidden” (See: [[rc://*/ta/man/translate/figs-activepassive]])',
      },
      {
        Reference: '1:26',
        ID: 'z8gv',
        Tags: '',
        SupportReference: '',
        Quote: 'ἀπὸ τῶν αἰώνων καὶ ἀπὸ τῶν γενεῶν',
        Occurrence: '1',
        Note: 'The words “ages” and “generations” refer to the time period from the creation of the world until the time when the gospel was preached.',
      },
      {
        Reference: '1:26',
        ID: 'a9kw',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'νῦν & ἐφανερώθη',
        Occurrence: '1',
        Note: 'This can be stated in active form. Alternate translation: “now God has revealed it” (See: [[rc://*/ta/man/translate/figs-activepassive]])',
      },
    ],
    27: [
      {
        Reference: '1:27',
        ID: 'c8yb',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'τὸ πλοῦτος τῆς δόξης τοῦ μυστηρίου τούτου',
        Occurrence: '1',
        Note: 'Paul speaks of the value of this secret truth about God as if it were a treasure of material wealth. “riches” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:27',
        ID: 'c7ln',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'Χριστὸς ἐν ὑμῖν',
        Occurrence: '1',
        Note: 'Paul speaks of the believers as if they were actual containers in which Christ is present. This is one of his ways of expressing the union of the believers with Christ. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '1:27',
        ID: 'mr83',
        Tags: '',
        SupportReference: '',
        Quote: 'ἡ ἐλπὶς τῆς δόξης',
        Occurrence: '1',
        Note: '“so you can confidently expect to share in God’s glory”',
      },
    ],
    28: [
      {
        Reference: '1:28',
        ID: 'va1x',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: 'ἡμεῖς καταγγέλλομεν, νουθετοῦντες & διδάσκοντες & παραστήσωμεν',
        Occurrence: '1',
        Note: 'These words do not include the Colossians. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
      {
        Reference: '1:28',
        ID: 'na8w',
        Tags: '',
        SupportReference: '',
        Quote: 'νουθετοῦντες πάντα ἄνθρωπον',
        Occurrence: '1',
        Note: '“We warn everyone”',
      },
      {
        Reference: '1:28',
        ID: 'lyz1',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-explicit',
        Quote: 'ἵνα παραστήσωμεν πάντα ἄνθρωπον',
        Occurrence: '1',
        Note: 'You may need to make explicit to whom they will present every person. Alternate translation: “so that we may present to God every person” (See: [[rc://*/ta/man/translate/figs-explicit]])',
      },
      {
        Reference: '1:28',
        ID: 'uk2i',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'τέλειον',
        Occurrence: '1',
        Note: 'Being complete is a metaphor for being spiritually mature. Alternate translation: “spiritually mature” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    intro: [
      {
        Reference: '1:intro',
        ID: 'gtm3',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: '# Colossians 01 General Notes\\n## Structure and formatting\\n\\nAs in a typical letter, Paul begins his letter in verses 1-2 by introducing Timothy and himself to the Christians in Colossae.\\n\\nPaul writes much of this chapter around two subjects: who Christ is, and what Christ has done for the Christian.\\n\\n## Special concepts in this chapter\\n\\n### Secret truth\\n\\nPaul refers to a “secret truth” in this chapter. The role of the church in the plans of God was once unknown. But God has now revealed it. Part of this involves the Gentiles having equal standing with the Jews in the plans of God. (See: [[rc://*/tw/dict/bible/kt/reveal]])\\n\\n## Important figures of speech in this chapter\\n\\n### Images for Christian living\\nPaul uses many different images to describe Christian living. In this chapter, he uses the images of “walking” and “bearing fruit.” (See: [[rc://*/tw/dict/bible/other/fruit]])\\n\\n## Other possible translation difficulties in this chapter\\n\\n### Paradox\\n\\nA paradox is a true statement that appears to describe something impossible. Verse 24 is a paradox: “Now I rejoice in my sufferings for you.” People do not usually rejoice when they suffer. But in verses 25-29 Paul explains why his suffering is good. ([Colossians 1:24](../../col/01/24.md))',
      },
    ],
  },
  2: {
    1: [
      {
        Reference: '2:1',
        ID: 'tt6v',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul continues to encourage the believers in Colossae and Laodicea to understand that Christ is God and that he lives in believers, so they should live in the same way they received him.',
      },
      {
        Reference: '2:1',
        ID: 'dqg5',
        Tags: '',
        SupportReference: '',
        Quote: 'ἡλίκον ἀγῶνα ἔχω ὑπὲρ ὑμῶν',
        Occurrence: '1',
        Note: 'Paul has exerted much effort in developing their purity and understanding of the gospel.',
      },
      {
        Reference: '2:1',
        ID: 'fn4z',
        Tags: '',
        SupportReference: '',
        Quote: 'τῶν ἐν Λαοδικίᾳ',
        Occurrence: '1',
        Note: 'This was a city very close to Colossae where there was also a church for which Paul was praying.',
      },
      {
        Reference: '2:1',
        ID: 'rj7d',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-synecdoche',
        Quote: 'ὅσοι οὐχ ἑόρακαν τὸ πρόσωπόν μου ἐν σαρκί',
        Occurrence: '1',
        Note: 'Here “face in the flesh” represents the person as a whole. Alternate translation: “all those who have never seen me personally” or “all those whom I have never met face to face” (See: [[rc://*/ta/man/translate/figs-synecdoche]])',
      },
    ],
    2: [
      {
        Reference: '2:2',
        ID: 'ge1w',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-pronouns',
        Quote: 'ἵνα & αἱ καρδίαι αὐτῶν',
        Occurrence: '1',
        Note: 'Paul includes the Galatians even though he uses a different pronoun. Alternate translation: “so that their hearts and yours” (See: [[rc://*/ta/man/translate/figs-pronouns]])',
      },
      {
        Reference: '2:2',
        ID: 'a4px',
        Tags: '',
        SupportReference: '',
        Quote: 'συμβιβασθέντες',
        Occurrence: '1',
        Note: 'This means brought together in a close relationship.',
      },
      {
        Reference: '2:2',
        ID: 'kdg8',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'πᾶν πλοῦτος τῆς πληροφορίας τῆς συνέσεως',
        Occurrence: '1',
        Note: 'Paul speaks of a person who is completely sure that the good news is true as though that person were rich in physical things. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:2',
        ID: 'qgi2',
        Tags: '',
        SupportReference: '',
        Quote: 'τοῦ μυστηρίου τοῦ Θεοῦ',
        Occurrence: '1',
        Note: 'This is knowledge that can be revealed only by God.',
      },
      {
        Reference: '2:2',
        ID: 'v13e',
        Tags: '',
        SupportReference: '',
        Quote: 'Χριστοῦ',
        Occurrence: '1',
        Note: 'Jesus Christ is the secret truth revealed by God.',
      },
    ],
    3: [
      {
        Reference: '2:3',
        ID: 'w74d',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'ἐν ᾧ εἰσιν πάντες οἱ θησαυροὶ τῆς σοφίας καὶ γνώσεως ἀπόκρυφοι',
        Occurrence: '1',
        Note: 'Only Christ can reveal God’s true wisdom and knowledge. This can be stated in active form. Alternate translation: “God has hidden all the treasures of wisdom and knowledge in Christ” (See: [[rc://*/ta/man/translate/figs-activepassive]])',
      },
      {
        Reference: '2:3',
        ID: 'w4mr',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'οἱ θησαυροὶ τῆς σοφίας καὶ γνώσεως',
        Occurrence: '1',
        Note: 'Paul speaks of God’s wisdom and knowledge as if they were material wealth. Alternate translation: “the very precious wisdom and knowledge” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:3',
        ID: 'vd98',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-doublet',
        Quote: 'τῆς σοφίας καὶ γνώσεως',
        Occurrence: '1',
        Note: 'These words mean basically the same thing here. Paul uses them together to emphasize that all spiritual understanding comes from Christ. (See: [[rc://*/ta/man/translate/figs-doublet]])',
      },
    ],
    4: [
      {
        Reference: '2:4',
        ID: 'j8di',
        Tags: '',
        SupportReference: '',
        Quote: 'παραλογίζηται',
        Occurrence: '1',
        Note: 'This means to cause someone to believe something that is not true, so he acts on that belief, and suffers harm as a result.',
      },
      {
        Reference: '2:4',
        ID: 'y4r3',
        Tags: '',
        SupportReference: '',
        Quote: 'πιθανολογίᾳ',
        Occurrence: '1',
        Note: 'speech that will make a person think differently',
      },
    ],
    5: [
      {
        Reference: '2:5',
        ID: 'g1rp',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'τῇ σαρκὶ ἄπειμι',
        Occurrence: '1',
        Note: 'The person’s flesh, or physical body, is a metonym for the person. Alternate translation: “not physically present with you” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
      {
        Reference: '2:5',
        ID: 'bz56',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-idiom',
        Quote: 'τῷ πνεύματι σὺν ὑμῖν εἰμι',
        Occurrence: '1',
        Note: 'Being with someone in spirit is a metaphor for thinking continually about that person. Alternate translation: “I continually think about you” (See: [[rc://*/ta/man/translate/figs-idiom]])',
      },
      {
        Reference: '2:5',
        ID: 'ev9p',
        Tags: '',
        SupportReference: '',
        Quote: 'τὴν τάξιν',
        Occurrence: '1',
        Note: 'doing things properly',
      },
      {
        Reference: '2:5',
        ID: 'hth1',
        Tags: '',
        SupportReference: '',
        Quote: 'τὸ στερέωμα & πίστεως ὑμῶν',
        Occurrence: '1',
        Note: '“how nothing and no one can cause you to stop believing”',
      },
    ],
    6: [
      {
        Reference: '2:6',
        ID: 'm3f1',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐν αὐτῷ περιπατεῖτε',
        Occurrence: '1',
        Note: 'Walking on a path is a metaphor for how a person lives his life. The words “in him” refer to being in close relationship with Christ and so doing what pleases him. Alternate translation: “live your lives the way he wants you to” or “live so that people can see that you belong to him” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    7: [
      {
        Reference: '2:7',
        ID: 'e2x6',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-idiom',
        Quote: 'ἐρριζωμένοι & ἐποικοδομούμενοι & βεβαιούμενοι & περισσεύοντες',
        Occurrence: '1',
        Note: 'These words explain what it means to “walk in him.” (See: [[rc://*/ta/man/translate/figs-idiom]])',
      },
      {
        Reference: '2:7',
        ID: 'fw47',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐρριζωμένοι & ἐν αὐτῷ',
        Occurrence: '1',
        Note: 'Paul speaks of a person with true faith in Christ as if that person were a tree growing in solid ground with deep roots. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:7',
        ID: 'tb5m',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐποικοδομούμενοι ἐν αὐτῷ',
        Occurrence: '1',
        Note: 'Paul speaks of a person with true faith in Christ as if that person were a building that has a strong foundation. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:7',
        ID: 'yh83',
        Tags: '',
        SupportReference: '',
        Quote: 'βεβαιούμενοι τῇ πίστει',
        Occurrence: '1',
        Note: '“trust in Jesus for everything”',
      },
      {
        Reference: '2:7',
        ID: 'l1is',
        Tags: '',
        SupportReference: '',
        Quote: 'καθὼς ἐδιδάχθητε',
        Occurrence: '1',
        Note: 'This is best stated without naming or otherwise calling attention to the teacher, who was Epaphras ([Colossians 1:7](../01/07.md)). Alternate translation: “just as you learned” or “just as they taught you” or “just as he taught you”',
      },
      {
        Reference: '2:7',
        ID: 'j47d',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'περισσεύοντες ἐν εὐχαριστίᾳ',
        Occurrence: '1',
        Note: 'Paul speaks of thanksgiving as if it were objects that a person could obtain more of. Alternate translation: “be very thankful to God” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    8: [
      {
        Reference: '2:8',
        ID: 'cbw5',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul urges the believers to be careful not to turn to the words and rules of others because nothing can add to the fullness of God that believers have in Christ.',
      },
      {
        Reference: '2:8',
        ID: 'lm1v',
        Tags: '',
        SupportReference: '',
        Quote: 'βλέπετε',
        Occurrence: '1',
        Note: '“Make sure that”',
      },
      {
        Reference: '2:8',
        ID: 'ga9l',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὑμᾶς ἔσται ὁ συλαγωγῶν',
        Occurrence: '1',
        Note: 'Paul speaks of the way a person can believe false teachings (because they believe false things or love the wrong things) as if someone had physically caught and held that person by force. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:8',
        ID: 'p3vx',
        Tags: '',
        SupportReference: '',
        Quote: 'τῆς φιλοσοφίας',
        Occurrence: '1',
        Note: 'religious doctrines and beliefs that are not from God’s word but are based on man’s thoughts about God and life',
      },
      {
        Reference: '2:8',
        ID: 't8xx',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'κενῆς ἀπάτης',
        Occurrence: '1',
        Note: 'Paul speaks of false ideas that produce nothing and so are without value as though they are containers with nothing in them. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:8',
        ID: 'l9jt',
        Tags: '',
        SupportReference: '',
        Quote: 'τὴν παράδοσιν τῶν ἀνθρώπων & τὰ στοιχεῖα τοῦ κόσμου',
        Occurrence: '1',
        Note: 'Both Jewish traditions and pagan (Gentile) belief systems are worthless. “The elements of the world” perhaps refers to evil spirits that claimed to rule the world and that were adored by people. But some interpreters view “the elements of the world” as people’s basic teachings about the world.',
      },
    ],
    9: [
      {
        Reference: '2:9',
        ID: 'ahq5',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐν αὐτῷ κατοικεῖ πᾶν τὸ πλήρωμα τῆς Θεότητος σωματικῶς',
        Occurrence: '1',
        Note: '“God’s total nature lives in physical form in Christ”',
      },
    ],
    10: [
      {
        Reference: '2:10',
        ID: 'lbk7',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐστὲ ἐν αὐτῷ πεπληρωμένοι',
        Occurrence: '1',
        Note: 'Paul speaks of people as though they were containers into which God has placed Christ. Alternate translation: “You are made complete in Christ” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:10',
        ID: 'je36',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὅς ἐστιν ἡ κεφαλὴ πάσης ἀρχῆς καὶ ἐξουσίας',
        Occurrence: '1',
        Note: 'Christ is the ruler over every other ruler (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    11: [
      {
        Reference: '2:11',
        ID: 'xeq7',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐν ᾧ καὶ περιετμήθητε',
        Occurrence: '1',
        Note: 'Paul is speaking of those who belong to Christ as if they were inside Christ’s body. This can also be made active. Alternate translation: “When you joined the church in baptism, God circumcised you” (See: [[rc://*/ta/man/translate/figs-metaphor]] and [[rc://*/ta/man/translate/figs-activepassive]])',
      },
      {
        Reference: '2:11',
        ID: 'ii43',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'περιτομῇ ἀχειροποιήτῳ',
        Occurrence: '1',
        Note: 'With this metaphor, Paul says that God has made Christian believers acceptable to himself in a way that reminded him of circumcision, the ceremony through which Hebrew male babies were added to the community of Israel. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    12: [
      {
        Reference: '2:12',
        ID: 'ln8e',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'συνταφέντες αὐτῷ ἐν τῷ βαπτισμῷ',
        Occurrence: '1',
        Note: 'Paul speaks of being baptized and joining the assembly of believers as if it were being buried with Christ. This can be made active. Alternate translation: “God buried you with Christ when you joined the church in baptism” (See: [[rc://*/ta/man/translate/figs-metaphor]] and [[rc://*/ta/man/translate/figs-activepassive]])',
      },
      {
        Reference: '2:12',
        ID: 'g1rq',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐν ᾧ & συνηγέρθητε',
        Occurrence: '1',
        Note: 'With this metaphor, Paul speaks of the new spiritual life of believers that God made possible by making Christ come alive again. This can be made active. Alternate translation: “because you have joined yourself to Christ, God raised you up” or “in him God caused you to live again” (See: [[rc://*/ta/man/translate/figs-metaphor]] and [[rc://*/ta/man/translate/figs-activepassive]])',
      },
      {
        Reference: '2:12',
        ID: 'rec6',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'συνηγέρθητε',
        Occurrence: '1',
        Note: 'Here to raise up is an idiom for causing someone who has died to become alive again. This can be stated in active form. Alternate translation: “God raised you up” or “God caused you to live again” (See: [[rc://*/ta/man/translate/figs-activepassive]] and [[rc://*/ta/man/translate/figs-idiom]])',
      },
    ],
    13: [
      {
        Reference: '2:13',
        ID: 'v6vi',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὑμᾶς νεκροὺς ὄντας',
        Occurrence: '1',
        Note: 'Paul speaks of unresponsiveness to God as if it were death. Alternate translation: “When you Colossian believers were unable to respond to God” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:13',
        ID: 'f9ms',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὑμᾶς νεκροὺς ὄντας & συνεζωοποίησεν ὑμᾶς',
        Occurrence: '1',
        Note: 'With this metaphor Paul speaks of coming into new spiritual life as if it were coming back to life physically. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:13',
        ID: 'wh4z',
        Tags: '',
        SupportReference: '',
        Quote:
          'νεκροὺς & ἐν τοῖς παραπτώμασιν καὶ τῇ ἀκροβυστίᾳ τῆς σαρκὸς ὑμῶν',
        Occurrence: '1',
        Note: 'You were dead on two accounts: (1) you were spiritually dead, living a life of sin against Christ and (2) you were not circumcised according to the law of Moses.',
      },
      {
        Reference: '2:13',
        ID: 'k2hw',
        Tags: '',
        SupportReference: '',
        Quote: 'χαρισάμενος ἡμῖν πάντα τὰ παραπτώματα',
        Occurrence: '1',
        Note: '“he forgave us, both us Jews and you Gentiles, of all our trespasses”',
      },
    ],
    14: [
      {
        Reference: '2:14',
        ID: 'w22z',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote:
          'ἐξαλείψας τὸ καθ’ ἡμῶν χειρόγραφον τοῖς δόγμασιν, ὃ ἦν ὑπεναντίον ἡμῖν',
        Occurrence: '1',
        Note: 'Paul speaks of the way God forgives our sins as if it were the way a person, to whom many people owe money or goods, destroys the record of that debt so they do not have to pay him back. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    15: [
      {
        Reference: '2:15',
        ID: 'gh24',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐδειγμάτισεν ἐν παρρησίᾳ',
        Occurrence: '1',
        Note: 'In Roman times, it was common practice for the Roman armies to have a victory parade when they returned home, displaying all the prisoners they had captured and goods they had obtained. God was victorious over the evil powers and authorities. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:15',
        ID: 'cg37',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'ἐν αὐτῷ',
        Occurrence: '1',
        Note: 'Here “the cross” stands for Christ’s death on the cross. (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    16: [
      {
        Reference: '2:16',
        ID: 'cii9',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐν βρώσει, καὶ ἐν πόσει',
        Occurrence: '1',
        Note: 'The law of Moses included what one can eat and drink. “for what you eat or what you drink”',
      },
      {
        Reference: '2:16',
        ID: 'b4kd',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐν μέρει ἑορτῆς, ἢ νουμηνίας, ἢ Σαββάτων',
        Occurrence: '1',
        Note: 'The law of Moses specified the days to celebrate, to worship, and to offer sacrifice. “for the way you celebrate feast days or new moons or the Sabbath”',
      },
    ],
    17: [
      {
        Reference: '2:17',
        ID: 'ip3a',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἅ ἐστιν σκιὰ τῶν μελλόντων, τὸ δὲ σῶμα τοῦ Χριστοῦ',
        Occurrence: '1',
        Note: 'A shadow shows the shape of an object, but it is not the object itself. In a similar way, the festivals, celebrations, and Sabbath show us something about how God would save people, but those things do not save people. The savior is Christ. Alternate translation: “These are like a shadow of what would happen, but the reality is Christ” or “These are like a shadow of the savior who would come, but the savior is Christ” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    18: [
      {
        Reference: '2:18',
        ID: 'zv2t',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'μηδεὶς ὑμᾶς καταβραβευέτω',
        Occurrence: '1',
        Note: 'Here Paul refers to false teachers as if they were corrupt judges at an athletic contest who would unjustly disqualify the believers from winning the prizes they deserve, and he speaks of Christ saving a person as if Christ were giving a prize to the winner of such a contest. Alternate translation: “Let no one … disqualify you from winning a prize” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:18',
        ID: 'b5ce',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'θέλων & ταπεινοφροσύνῃ',
        Occurrence: '1',
        Note: 'The word “humility” is a metonym for actions one does to make others think that one is humble. Alternate translation: “who wants you to do things to show that you are humble” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
      {
        Reference: '2:18',
        ID: 'kn5d',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἃ ἑόρακεν ἐμβατεύων',
        Occurrence: '1',
        Note: 'Here Paul speaks about people who claim to have dreams and visions from God and who talk proudly about them. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:18',
        ID: 'p7q4',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'φυσιούμενος ὑπὸ τοῦ νοὸς τῆς σαρκὸς αὐτοῦ',
        Occurrence: '1',
        Note: 'Here Paul says that sinful ways of thinking make a person arrogant. Alternate translation: “puffs himself up by means of his fleshly thinking” (See: [[rc://*/ta/man/translate/figs-activepassive]])',
      },
      {
        Reference: '2:18',
        ID: 'wp42',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'φυσιούμενος',
        Occurrence: '1',
        Note: 'Here a person who boasts is spoken of as if he were an object into which someone had blown air to make it larger than it should be. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:18',
        ID: 'if94',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'τοῦ νοὸς τῆς σαρκὸς αὐτοῦ',
        Occurrence: '1',
        Note: 'Here the idea of flesh stands for the sinful human nature. “the sinful thoughts he naturally thinks” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    19: [
      {
        Reference: '2:19',
        ID: 'm2dz',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'οὐ κρατῶν τὴν κεφαλήν',
        Occurrence: '1',
        Note: 'A person not trusting in Christ is spoken of has if they do not hold firmly to the head. Christ is spoken of as if he were the head of a body. Alternate translation: “He does not firmly grasp Christ, who is like the head of a body” or “He does not cling to Christ, who is like the head of a body” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:19',
        ID: 'r4ca',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote:
          'ἐξ οὗ πᾶν τὸ σῶμα διὰ τῶν ἁφῶν καὶ συνδέσμων ἐπιχορηγούμενον καὶ συμβιβαζόμενον',
        Occurrence: '1',
        Note: 'Paul speaks of the church, which is ruled and empowered by Christ, as if it were a human body. Alternate translation: “It is from the head that God supplies the whole body throughout its joints and ligaments and holds it together” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    20: [
      {
        Reference: '2:20',
        ID: 'yg7h',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'εἰ ἀπεθάνετε σὺν Χριστῷ ἀπὸ τῶν στοιχείων τοῦ κόσμου',
        Occurrence: '1',
        Note: 'With this metaphor, Paul speaks of a believer as a person who is spiritually united with Christ: as Christ died, so the believer has spiritually died; as Christ has come back to life, so the believer has come back to spiritual life, that is, to responsiveness to God. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '2:20',
        ID: 'uu77',
        Tags: '',
        SupportReference: '',
        Quote: 'ὡς ζῶντες ἐν κόσμῳ δογματίζεσθε',
        Occurrence: '1',
        Note: '“think you must obey the desires of the world”',
      },
      {
        Reference: '2:20',
        ID: 'fe1k',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'τοῦ κόσμου',
        Occurrence: '1',
        Note: 'the thoughts, desires, and assumptions of the sinful majority of the world’s people (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    21: [
      {
        Reference: '2:21',
        ID: 'v9e7',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'The rhetorical question that begins with the words “why do you live as obligated to the world” in verse 20 ends here.',
      },
      {
        Reference: '2:21',
        ID: 'b392',
        Tags: '',
        SupportReference: '',
        Quote: 'μὴ ἅψῃ! μηδὲ γεύσῃ! μηδὲ θίγῃς!',
        Occurrence: '1',
        Note: 'Paul is quoting what other people have been telling the Colossians. “why do you believe them when they say, ‘Do not handle, nor taste, nor touch’?” or “you should not obey them when they say, ‘Do not handle, nor taste, nor touch’”',
      },
    ],
    23: [
      {
        Reference: '2:23',
        ID: 'y2dc',
        Tags: '',
        SupportReference: '',
        Quote:
          'ἅτινά ἐστιν λόγον μὲν ἔχοντα σοφίας ἐν ἐθελοθρησκείᾳ καὶ ταπεινοφροσύνῃ, ἀφειδίᾳ σώματος',
        Occurrence: '1',
        Note: '“These rules seem wise to unbelieving people because they allow those who follow them to appear humble because they hurt their own bodies”',
      },
      {
        Reference: '2:23',
        ID: 'e7p5',
        Tags: '',
        SupportReference: '',
        Quote: 'οὐκ ἐν τιμῇ τινι πρὸς πλησμονὴν τῆς σαρκός',
        Occurrence: '1',
        Note: '“do not help you stop following your human desires”',
      },
    ],
    intro: [
      {
        Reference: '2:intro',
        ID: 'p3uc',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: '# Colossians 02 General Notes\\n## Special concepts in this chapter\\n\\n### Circumcision and baptism\\nIn verses 11-12, Paul uses both the old covenant sign of circumcision and the new covenant sign of baptism to show how Christians are united with Christ and freed from sin.\\n\\n## Other possible translation difficulties in this chapter\\n\\n### Flesh\\n\\nThis is a complex issue. “Flesh” is possibly a metaphor for our sinful nature. Paul is not teaching that the physical part of man is sinful. Paul appears to be teaching that, while Christians are alive (“in the flesh”), we will continue to sin. But our new nature will be fighting against our old nature. Paul also uses “flesh” in this chapter to refer to the physical body.\\n\\n### Implicit information\\nPaul mentions several issues in this chapter that imply information about the context of the church in Colossae. It is best to allow the text to remain uncertain over the actual details. (See: [[rc://*/ta/man/translate/figs-explicit]])',
      },
    ],
  },
  3: {
    1: [
      {
        Reference: '3:1',
        ID: 'ya97',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul warns the believers that because they are one with Christ, they ought not do certain things.',
      },
      {
        Reference: '3:1',
        ID: 'r5yh',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-idiom',
        Quote: 'εἰ οὖν',
        Occurrence: '1',
        Note: 'This is an idiom that means “because.” (See: [[rc://*/ta/man/translate/figs-idiom]])',
      },
      {
        Reference: '3:1',
        ID: 't1jv',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-pastforfuture',
        Quote: 'συνηγέρθητε τῷ Χριστῷ',
        Occurrence: '1',
        Note: 'Here to raise up is an idiom for causing someone who has died to become alive again. Possible meanings are (1) because God has caused Christ to come alive again, God has already given the believers in Colossae new spiritual life. Alternate translation: “God has given you new life because you belong to Christ” or (2) because God has caused Christ to come alive again, the believers in Colossae can know that after they die they will live with Christ, and Paul can speak of the believers living again as if it has already happened. Alternate translation: “you can be sure that God will give you life as he has caused Christ to come alive again” (See: [[rc://*/ta/man/translate/figs-pastforfuture]] and [[rc://*/ta/man/translate/figs-idiom]])',
      },
      {
        Reference: '3:1',
        ID: 'p3fw',
        Tags: '',
        SupportReference: '',
        Quote: 'τὰ ἄνω',
        Occurrence: '1',
        Note: '“things in heaven”',
      },
    ],
    3: [
      {
        Reference: '3:3',
        ID: 'l9yk',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἀπεθάνετε γάρ',
        Occurrence: '1',
        Note: 'As Christ actually died, so God counts the Colossian believers as having died with Christ. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '3:3',
        ID: 'gkz6',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'ἡ ζωὴ ὑμῶν κέκρυπται σὺν τῷ Χριστῷ ἐν τῷ Θεῷ',
        Occurrence: '1',
        Note: 'Paul speaks of people’s lives as if they were objects that can be hidden in containers and speaks of God as if he were a container. Alternate translation: Possible meanings are (1) “it is as though God has taken your life and concealed it with Christ in God’s presence” or (2) “only God knows what your true life really is, and he will reveal it when he reveals Christ” (See: [[rc://*/ta/man/translate/figs-activepassive]] and [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    4: [
      {
        Reference: '3:4',
        ID: 'n4nj',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'ἡ ζωὴ ὑμῶν',
        Occurrence: '1',
        Note: 'Christ is the one who gives spiritual life to the believer. (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    5: [
      {
        Reference: '3:5',
        ID: 'p9w9',
        Tags: '',
        SupportReference: '',
        Quote: 'ἀκαθαρσίαν',
        Occurrence: '1',
        Note: 'impure behavior',
      },
      {
        Reference: '3:5',
        ID: 'e65k',
        Tags: '',
        SupportReference: '',
        Quote: 'πάθος',
        Occurrence: '1',
        Note: 'strong, lustful desire',
      },
      {
        Reference: '3:5',
        ID: 'h5v4',
        Tags: '',
        SupportReference: '',
        Quote: 'τὴν πλεονεξίαν, ἥτις ἐστὶν εἰδωλολατρία',
        Occurrence: '1',
        Note: '“greed, which is the same thing as idolatry” or “do not be greedy because that is the same as worshiping idols”',
      },
    ],
    6: [
      {
        Reference: '3:6',
        ID: 's9lm',
        Tags: '',
        SupportReference: '',
        Quote: 'ἡ ὀργὴ τοῦ Θεοῦ',
        Occurrence: '1',
        Note: 'God’s anger against those who do evil as shown by what he does to punish them.',
      },
    ],
    7: [
      {
        Reference: '3:7',
        ID: 'p4q8',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐν οἷς καὶ ὑμεῖς περιεπατήσατέ',
        Occurrence: '1',
        Note: 'Paul speaks of the way a person behaves as if it were a road or path a person walks on. Alternate translation: “These are the things you used to do” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '3:7',
        ID: 's824',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὅτε ἐζῆτε ἐν τούτοις',
        Occurrence: '1',
        Note: 'Possible meanings are (1) “when you practiced these things” or (2) “when you lived among the people who disobey God” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    8: [
      {
        Reference: '3:8',
        ID: 'd3wr',
        Tags: '',
        SupportReference: '',
        Quote: 'κακίαν',
        Occurrence: '1',
        Note: '“desire to do wicked deeds”',
      },
      {
        Reference: '3:8',
        ID: 'lgz1',
        Tags: '',
        SupportReference: '',
        Quote: 'βλασφημίαν',
        Occurrence: '1',
        Note: 'speech used to hurt others',
      },
      {
        Reference: '3:8',
        ID: 'f59z',
        Tags: '',
        SupportReference: '',
        Quote: 'αἰσχρολογίαν',
        Occurrence: '1',
        Note: 'words that do not belong in polite conversation',
      },
      {
        Reference: '3:8',
        ID: 'n23c',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'ἐκ τοῦ στόματος ὑμῶν',
        Occurrence: '1',
        Note: 'Here “mouth” is a metonym for talk. “in your talk” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    9: [
      {
        Reference: '3:9',
        ID: 'c6tk',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul continues to tell the believers how to live and reminds them that Christians should treat everyone according to the same standard.',
      },
      {
        Reference: '3:9',
        ID: 'vsd8',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἀπεκδυσάμενοι τὸν παλαιὸν ἄνθρωπον σὺν ταῖς πράξεσιν αὐτοῦ',
        Occurrence: '1',
        Note: 'Here Paul is speaking of a Christian’s rejecting his old sinful life as if it were an old garment that he takes off in order to put on a new garment. It was very common for Israelites such as Paul to speak of moral qualities as if they were pieces of clothing. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    10: [
      {
        Reference: '3:10',
        ID: 'brx6',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'καὶ ἐνδυσάμενοι τὸν νέον',
        Occurrence: '1',
        Note: 'Here Paul is speaking of a Christian’s rejecting his old sinful life as if it were an old garment that he takes off (verse 9) in order to put on a new garment. It was very common for Israelites such as Paul to speak of moral qualities as if they were pieces of clothing. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '3:10',
        ID: 'd15v',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'εἰκόνα',
        Occurrence: '1',
        Note: 'This refers to Jesus Christ. (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    11: [
      {
        Reference: '3:11',
        ID: 't2w2',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote:
          'οὐκ ἔνι Ἕλλην καὶ Ἰουδαῖος, περιτομὴ καὶ ἀκροβυστία, βάρβαρος, Σκύθης, δοῦλος, ἐλεύθερος',
        Occurrence: '1',
        Note: 'These terms are examples of the categories of people that Paul says do not matter for God. God sees every person alike, not by race, religion, nationality, or social status. Alternate translation: “race, religion, culture, and social status do not matter” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
      {
        Reference: '3:11',
        ID: 'vt4t',
        Tags: '',
        SupportReference: '',
        Quote: 'βάρβαρος',
        Occurrence: '1',
        Note: 'a foreigner who does not know local customs',
      },
      {
        Reference: '3:11',
        ID: 'n7by',
        Tags: '',
        SupportReference: '',
        Quote: 'Σκύθης',
        Occurrence: '1',
        Note: 'This is someone from the land of Scythia, which was outside the Roman Empire. Greeks and Romans used this word for someone who grew up in a place where everyone did wicked things all the time.',
      },
      {
        Reference: '3:11',
        ID: 'i964',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-explicit',
        Quote: 'ἀλλὰ πάντα καὶ ἐν πᾶσιν Χριστός',
        Occurrence: '1',
        Note: 'Nothing is excluded or left out of the rule of Christ. Alternate translation: “Christ is all important and lives in all his people” (See: [[rc://*/ta/man/translate/figs-explicit]])',
      },
    ],
    12: [
      {
        Reference: '3:12',
        ID: 'b5ti',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-activepassive',
        Quote: 'ὡς ἐκλεκτοὶ τοῦ Θεοῦ ἅγιοι καὶ ἠγαπημένοι',
        Occurrence: '1',
        Note: 'This can be made active. Alternate translation: “as those whom God has chosen for himself, whom he desires to see live for him alone, and whom he loves” (See: [[rc://*/ta/man/translate/figs-activepassive]])',
      },
      {
        Reference: '3:12',
        ID: 'd217',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote:
          'ἐνδύσασθε & σπλάγχνα οἰκτιρμοῦ, χρηστότητα, ταπεινοφροσύνην, πραΰτητα, μακροθυμίαν',
        Occurrence: '1',
        Note: 'The “heart” is a metaphor for feelings and attitudes. Here it is spoken of as if it has certain feelings and attitudes, and as if it were clothing to wear. Alternate translation: “have a merciful, kind, humble, gentle, and patient heart” or “be merciful, kind, humble, gentle, and patient” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    13: [
      {
        Reference: '3:13',
        ID: 'r8iy',
        Tags: '',
        SupportReference: '',
        Quote: 'ἀνεχόμενοι ἀλλήλων',
        Occurrence: '1',
        Note: '“Be patient with one another” or “Accept each other even when you disappoint each other”',
      },
      {
        Reference: '3:13',
        ID: 'rts1',
        Tags: '',
        SupportReference: '',
        Quote: 'χαριζόμενοι ἑαυτοῖς',
        Occurrence: '1',
        Note: '“Treat each other better than they deserve for you to treat them”',
      },
      {
        Reference: '3:13',
        ID: 'p474',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-abstractnouns',
        Quote: 'πρός & ἔχῃ μομφήν',
        Occurrence: '1',
        Note: 'The abstract noun “complaint” can be stated as “complain.” Alternate translation: “has a reason to complain against” (See: [[rc://*/ta/man/translate/figs-abstractnouns]])',
      },
    ],
    14: [
      {
        Reference: '3:14',
        ID: 'x5g8',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'τὴν ἀγάπην, ὅ ἐστιν σύνδεσμος τῆς τελειότητος',
        Occurrence: '1',
        Note: 'Here “bond of perfection” is a metaphor for something that causes perfect unity among people. Alternate translation: “love one another because it will unite you perfectly together. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    15: [
      {
        Reference: '3:15',
        ID: 'hdg5',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'ἡ εἰρήνη τοῦ Χριστοῦ βραβευέτω ἐν ταῖς καρδίαις ὑμῶν',
        Occurrence: '1',
        Note: 'Paul speaks of the peace that Christ gives as if it were a ruler. Possible meanings are (1) “Do everything so that you can have peaceful relationships with each other” or (2) “Allow God to give you peace in your heart” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
      {
        Reference: '3:15',
        ID: 'i9hg',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'ἐν ταῖς καρδίαις ὑμῶν',
        Occurrence: '1',
        Note: 'Here “hearts” is a metonym for a people’s minds or inner being. Alternate translation: “in your minds” or “inside of you” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    16: [
      {
        Reference: '3:16',
        ID: 'w9dv',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὁ λόγος τοῦ Χριστοῦ ἐνοικείτω ἐν ὑμῖν',
        Occurrence: '1',
        Note: 'Paul speaks of Christ’s word as if it were a person capable of living inside other people. “Word of Christ” here is a metonym for the teachings of Christ. Alternate translation: “Be obedient to the instructions of Christ” or “Always trust Christ’s promises” (See: [[rc://*/ta/man/translate/figs-metaphor]] and [[rc://*/ta/man/translate/figs-metonymy]])',
      },
      {
        Reference: '3:16',
        ID: 'h5k9',
        Tags: '',
        SupportReference: '',
        Quote: 'νουθετοῦντες ἑαυτοὺς',
        Occurrence: '1',
        Note: '“caution and encourage one another”',
      },
      {
        Reference: '3:16',
        ID: 'ubi5',
        Tags: '',
        SupportReference: '',
        Quote: 'ψαλμοῖς, ὕμνοις, ᾠδαῖς πνευματικαῖς',
        Occurrence: '1',
        Note: '“with all sorts of songs to praise God”',
      },
      {
        Reference: '3:16',
        ID: 'cnj1',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'ἐν τῇ χάριτι, ᾄδοντες ἐν ταῖς καρδίαις ὑμῶν',
        Occurrence: '1',
        Note: 'Here “hearts” is a metonym for people’s minds or inner being. Alternate translation: “Sing with thankfulness in your minds” or “Sing and be thankful” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    17: [
      {
        Reference: '3:17',
        ID: 'g8p8',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐν λόγῳ ἢ ἐν ἔργῳ',
        Occurrence: '1',
        Note: '“in speaking or in acting”',
      },
      {
        Reference: '3:17',
        ID: 'uix9',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'ἐν ὀνόματι Κυρίου Ἰησοῦ',
        Occurrence: '1',
        Note: 'Acting in the name of a person here is a metonym for acting to help other people think well of that person. Alternate translation: “to honor the Lord Jesus” or “so that others will know you belong to the Lord Jesus and think well of him” or “as if the Lord Jesus himself were doing it” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
      {
        Reference: '3:17',
        ID: 'bv84',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'δι’ αὐτοῦ',
        Occurrence: '1',
        Note: 'Possible meanings are (1) because he has done great deeds or (2) because he has made it possible for people to speak to God and so give him thanks. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    18: [
      {
        Reference: '3:18',
        ID: 'flu9',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul then gives some special instructions to wives, husbands, children, fathers, slaves, and masters.',
      },
      {
        Reference: '3:18',
        ID: 'tt9u',
        Tags: '',
        SupportReference: '',
        Quote: 'αἱ γυναῖκες, ὑποτάσσεσθε τοῖς',
        Occurrence: '1',
        Note: '“Wives, obey”',
      },
      {
        Reference: '3:18',
        ID: 'b2y3',
        Tags: '',
        SupportReference: '',
        Quote: 'ἀνῆκεν',
        Occurrence: '1',
        Note: '“it is proper” or “it is right”',
      },
    ],
    19: [
      {
        Reference: '3:19',
        ID: 'lc4a',
        Tags: '',
        SupportReference: '',
        Quote: 'μὴ πικραίνεσθε πρὸς',
        Occurrence: '1',
        Note: '“do not be harsh with” or “do not be angry toward”',
      },
    ],
    21: [
      {
        Reference: '3:21',
        ID: 'bvi3',
        Tags: '',
        SupportReference: '',
        Quote: 'μὴ ἐρεθίζετε τὰ τέκνα ὑμῶν',
        Occurrence: '1',
        Note: '“do not needlessly make your children angry”',
      },
    ],
    22: [
      {
        Reference: '3:22',
        ID: 'cx6a',
        Tags: '',
        SupportReference: '',
        Quote: 'ὑπακούετε & τοῖς κατὰ σάρκα κυρίοις',
        Occurrence: '1',
        Note: '“obey your human masters”',
      },
      {
        Reference: '3:22',
        ID: 'iy1n',
        Tags: '',
        SupportReference: '',
        Quote: 'πάντα & μὴ ἐν ὀφθαλμοδουλεία, ὡς ἀνθρωπάρεσκοι',
        Occurrence: '1',
        Note: '“things. Do not obey only when your master is watching, as though you need only to please people”',
      },
      {
        Reference: '3:22',
        ID: 'r22m',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'ἐν ἁπλότητι καρδίας',
        Occurrence: '1',
        Note: '“Heart” here is a metonym for a person’s thoughts or intentions. Alternate translation: “with all honest intentions” or “with sincerity” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    23: [
      {
        Reference: '3:23',
        ID: 'arw4',
        Tags: '',
        SupportReference: '',
        Quote: 'ὡς τῷ Κυρίῳ',
        Occurrence: '1',
        Note: '“as you would work for the Lord”',
      },
    ],
    24: [
      {
        Reference: '3:24',
        ID: 'f3ed',
        Tags: '',
        SupportReference: '',
        Quote: 'τὴν ἀνταπόδοσιν τῆς κληρονομίας',
        Occurrence: '1',
        Note: '“the inheritance as your reward”',
      },
      {
        Reference: '3:24',
        ID: 'p3pw',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'κληρονομίας',
        Occurrence: '1',
        Note: 'Receiving what God has promised believers is spoken of as if it were inheriting property and wealth from a family member. (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    25: [
      {
        Reference: '3:25',
        ID: 'u5lx',
        Tags: '',
        SupportReference: '',
        Quote: 'ὁ & ἀδικῶν, κομιεῖται ὃ ἠδίκησεν',
        Occurrence: '1',
        Note: 'The phrase “receive the penalty” means to be punished. Alternate translation: “anyone who does unrighteousness will be punished” or “God will punish anyone who does what is unrighteous”',
      },
      {
        Reference: '3:25',
        ID: 'ak8j',
        Tags: '',
        SupportReference: '',
        Quote: 'ἀδικῶν',
        Occurrence: '1',
        Note: 'who actively does wrong of any kind',
      },
      {
        Reference: '3:25',
        ID: 'c9fx',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-abstractnouns',
        Quote: 'οὐκ ἔστιν προσωπολημψία',
        Occurrence: '1',
        Note: 'The abstract noun “favoritism” can be expressed with the verb “favor.” To favor some people is to judge them by different standards so the result is better for them than for others who do the same actions. Alternate translation: “God does not favor anyone” or “God judges everyone by the same standard” (See: [[rc://*/ta/man/translate/figs-abstractnouns]])',
      },
    ],
    intro: [
      {
        Reference: '3:intro',
        ID: 'qtl2',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: '# Colossians 03 General Notes\\n## Structure and formatting\\n\\nThe second part of this chapter parallels Ephesians 5 and 6.\\n\\n## Special concepts in this chapter\\n\\n### Old and new self\\nThe old and new self mean the same as the old and new man. The term “old man” probably refers to the sinful nature with which a person is born. The “new man” is the new nature or new life that God gives a person after they come to believe in Christ. (See: [[rc://*/tw/dict/bible/kt/sin]] and [[rc://*/tw/dict/bible/kt/faith]])\\n\\n## Other possible translation difficulties in this chapter\\n\\n### Character\\nMany of the things Paul encourages his readers to pursue or avoid are not actions but character qualities. Because of this, they may be difficult to translate. (See: [[rc://*/ta/man/translate/figs-abstractnouns]])\\n\\n### “The things above”\\n\\nWhere God dwells is often pictured as being located “above.” Paul says to “seek the things above” and to “think about the things above.” He is implying Christians should seek and think about heavenly and godly things.',
      },
    ],
  },
  4: {
    1: [
      {
        Reference: '4:1',
        ID: 'qhd2',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'After speaking to masters, Paul ends his special instructions to the different kinds of believers in the church at Colossae.',
      },
      {
        Reference: '4:1',
        ID: 'ae3y',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-doublet',
        Quote: 'τὸ δίκαιον καὶ τὴν ἰσότητα',
        Occurrence: '1',
        Note: 'These words mean almost the same thing and are used to emphasize the things that are morally correct. (See: [[rc://*/ta/man/translate/figs-doublet]])',
      },
      {
        Reference: '4:1',
        ID: 't9wy',
        Tags: '',
        SupportReference: '',
        Quote: 'καὶ ὑμεῖς ἔχετε Κύριον ἐν οὐρανῷ',
        Occurrence: '1',
        Note: 'God wants the relationship between an earthly master and his slave to be loving the way God, the heavenly master, loves his earthly servants, including the earthly slaves’ masters.',
      },
    ],
    2: [
      {
        Reference: '4:2',
        ID: 'sct4',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: '',
        Occurrence: '0',
        Note: 'Here the word “us” refers to Paul and Timothy but not the Colossians. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
      {
        Reference: '4:2',
        ID: 'wx86',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul continues to give instructions to believers on how to live and speak.',
      },
      {
        Reference: '4:2',
        ID: 'pp1c',
        Tags: '',
        SupportReference: '',
        Quote: 'τῇ προσευχῇ προσκαρτερεῖτε',
        Occurrence: '1',
        Note: '“Keep praying faithfully” or “Keep praying consistently”',
      },
    ],
    3: [
      {
        Reference: '4:3',
        ID: 'ub1i',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὁ Θεὸς ἀνοίξῃ & θύραν',
        Occurrence: '1',
        Note: 'Opening a door for someone is a metaphor for giving that person the opportunity to do something. Alternate translation: “God would provide opportunities” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '4:3',
        ID: 'lj4f',
        Tags: '',
        SupportReference: '',
        Quote: 'ἀνοίξῃ & θύραν τοῦ λόγου',
        Occurrence: '1',
        Note: '“make an opportunity for us tp preach his message”',
      },
      {
        Reference: '4:3',
        ID: 'ce37',
        Tags: '',
        SupportReference: '',
        Quote: 'τὸ μυστήριον τοῦ Χριστοῦ',
        Occurrence: '1',
        Note: 'This refers to the gospel of Jesus Christ, which was not understood before Christ came.',
      },
      {
        Reference: '4:3',
        ID: 'q4jx',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'δι’ ὃ & δέδεμαι',
        Occurrence: '1',
        Note: 'Here “chained” is a metonym for being in prison. Alternate translation: “It is for proclaiming the message of Jesus Christ that I am now in prison” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    4: [
      {
        Reference: '4:4',
        ID: 'hm5w',
        Tags: '',
        SupportReference: '',
        Quote: 'ἵνα φανερώσω αὐτὸ',
        Occurrence: '1',
        Note: '“Pray that I might be able to speak the message of Jesus Christ clearly”',
      },
    ],
    5: [
      {
        Reference: '4:5',
        ID: 'z3ax',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ἐν σοφίᾳ περιπατεῖτε πρὸς τοὺς ἔξω',
        Occurrence: '1',
        Note: 'The idea of walking is often used for the idea of conducting one’s life. Alternate translation: “Live in such a way that those who are not believers will see that you are wise” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '4:5',
        ID: 'b525',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'τὸν καιρὸν ἐξαγοραζόμενοι',
        Occurrence: '1',
        Note: 'To “redeem” something means to restore it to it’s rightful owner. Here time is spoken of as something that can be restored and used to serve God. Alternate translation: “do the best things you can with your time” or “put the time to its best use” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    6: [
      {
        Reference: '4:6',
        ID: 'fuv5',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'ὁ λόγος ὑμῶν πάντοτε ἐν χάριτι, ἅλατι ἠρτυμένος',
        Occurrence: '1',
        Note: 'Food with salt is a metaphor for words that teach others and that others enjoy hearing. Alternate translation: “Let your conversation always be gracious and attractive” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
      {
        Reference: '4:6',
        ID: 'c1w4',
        Tags: '',
        SupportReference: '',
        Quote: 'εἰδέναι πῶς δεῖ ὑμᾶς & ἀποκρίνεσθαι',
        Occurrence: '1',
        Note: '“so that you may know how to answer questions from anyone about Jesus Christ” or “so that you may be able to treat every person well”',
      },
    ],
    7: [
      {
        Reference: '4:7',
        ID: 'vtb1',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Onesimus was a slave of Philemon in Colossae. He had stolen money from Philemon and run away to Rome where he became a Christian through the ministry of Paul. Now Tychicus and Onesimus are the ones bringing Paul’s letter to Colossae.',
      },
      {
        Reference: '4:7',
        ID: 'ut91',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul closes with special instructions about certain people as well as greetings to and from individual believers.',
      },
      {
        Reference: '4:7',
        ID: 'xzz4',
        Tags: '',
        SupportReference: '',
        Quote: 'τὰ κατ’ ἐμὲ',
        Occurrence: '1',
        Note: '“everything that has been happening to me”',
      },
      {
        Reference: '4:7',
        ID: 'p7c1',
        Tags: '',
        SupportReference: '',
        Quote: 'σύνδουλος',
        Occurrence: '1',
        Note: '“fellow servant.” Though Paul is a free man, he sees himself as a servant of Christ and sees Tychicus as a fellow servant.',
      },
    ],
    8: [
      {
        Reference: '4:8',
        ID: 'vyq5',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-exclusive',
        Quote: 'τὰ περὶ ἡμῶν',
        Occurrence: '1',
        Note: 'These words do not include the Colossians. (See: [[rc://*/ta/man/translate/figs-exclusive]])',
      },
      {
        Reference: '4:8',
        ID: 'fr1z',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metaphor',
        Quote: 'παρακαλέσῃ τὰς καρδίας ὑμῶν',
        Occurrence: '1',
        Note: 'The heart was thought to be the center of many emotions. Alternate translation: “may encourage you” (See: [[rc://*/ta/man/translate/figs-metaphor]])',
      },
    ],
    9: [
      {
        Reference: '4:9',
        ID: 'yqh9',
        Tags: '',
        SupportReference: '',
        Quote: 'τῷ πιστῷ καὶ ἀγαπητῷ ἀδελφῷ',
        Occurrence: '1',
        Note: 'Paul calls Onesimus a fellow Christian and servant of Christ.',
      },
      {
        Reference: '4:9',
        ID: 'n15d',
        Tags: '',
        SupportReference: '',
        Quote: 'γνωρίσουσιν',
        Occurrence: '1',
        Note: '“Tychicus and Onesimus will tell”',
      },
      {
        Reference: '4:9',
        ID: 'vb7j',
        Tags: '',
        SupportReference: '',
        Quote: 'πάντα & τὰ ὧδε',
        Occurrence: '1',
        Note: 'They will tell the Colossian believers all that is taking place where Paul is currently living. Tradition says Paul was in Rome under house arrest or in prison at this time.',
      },
    ],
    10: [
      {
        Reference: '4:10',
        ID: 'wmf4',
        Tags: '',
        SupportReference: '',
        Quote: 'Ἀρίσταρχος',
        Occurrence: '1',
        Note: 'He was in prison with Paul in Ephesus when Paul wrote this letter to the Colossians.',
      },
      {
        Reference: '4:10',
        ID: 'cg3a',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐὰν ἔλθῃ',
        Occurrence: '1',
        Note: '“if Mark comes”',
      },
    ],
    11: [
      {
        Reference: '4:11',
        ID: 'bm6s',
        Tags: '',
        SupportReference: '',
        Quote: 'Ἰησοῦς, ὁ λεγόμενος Ἰοῦστος',
        Occurrence: '1',
        Note: 'This is a man who also worked with Paul.',
      },
      {
        Reference: '4:11',
        ID: 'ci74',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote:
          'οἱ ὄντες ἐκ περιτομῆς οὗτοι, μόνοι συνεργοὶ εἰς τὴν Βασιλείαν τοῦ Θεοῦ',
        Occurrence: '1',
        Note: 'Paul uses “circumcision” here to refer to Jews because, under the Old Testament law, all male Jews had to be circumcised. Alternate translation: “These three men are the only Jewish believers working with me to proclaim God as king through Christ Jesus” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
      {
        Reference: '4:11',
        ID: 'p8e9',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐκ περιτομῆς οὗτοι, μόνοι',
        Occurrence: '1',
        Note: '“These men—Aristarchus, Mark, and Justus—alone of the circumcision”',
      },
    ],
    12: [
      {
        Reference: '4:12',
        ID: 'et2g',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Laodicea and Hierapolis were towns close to Colossae.',
      },
      {
        Reference: '4:12',
        ID: 'gg86',
        Tags: '',
        SupportReference: '',
        Quote: 'Ἐπαφρᾶς',
        Occurrence: '1',
        Note: 'Epaphras was the man who had preached the good news to the people in Colossae ([Colossians 1:7](../01/07.md)).',
      },
      {
        Reference: '4:12',
        ID: 'rq61',
        Tags: '',
        SupportReference: '',
        Quote: 'ὁ ἐξ ὑμῶν',
        Occurrence: '1',
        Note: '“from your city” or “your fellow townsman”',
      },
      {
        Reference: '4:12',
        ID: 'ek51',
        Tags: '',
        SupportReference: '',
        Quote: 'δοῦλος Χριστοῦ Ἰησοῦ',
        Occurrence: '1',
        Note: '“a committed disciple of Christ Jesus”',
      },
      {
        Reference: '4:12',
        ID: 'p8ff',
        Tags: '',
        SupportReference: '',
        Quote: 'πάντοτε ἀγωνιζόμενος ὑπὲρ ὑμῶν ἐν ταῖς προσευχαῖς',
        Occurrence: '1',
        Note: '“earnestly prays for you”',
      },
      {
        Reference: '4:12',
        ID: 'nuh9',
        Tags: '',
        SupportReference: '',
        Quote: 'σταθῆτε τέλειοι καὶ πεπληροφορημένοι',
        Occurrence: '1',
        Note: '“you may stand mature and confident”',
      },
    ],
    13: [
      {
        Reference: '4:13',
        ID: 'k8vv',
        Tags: '',
        SupportReference: '',
        Quote: 'μαρτυρῶ & αὐτῷ, ὅτι ἔχει πολὺν πόνον ὑπὲρ ὑμῶν',
        Occurrence: '1',
        Note: '“I have observed that he has worked very hard for you”',
      },
    ],
    14: [
      {
        Reference: '4:14',
        ID: 'hq1k',
        Tags: '',
        SupportReference: '',
        Quote: 'Δημᾶς',
        Occurrence: '1',
        Note: 'This is another co-worker with Paul.',
      },
    ],
    15: [
      {
        Reference: '4:15',
        ID: 'sc5g',
        Tags: '',
        SupportReference: '',
        Quote: 'τοὺς & ἀδελφοὺς',
        Occurrence: '1',
        Note: 'Here this means fellow Christians, including both men and women.',
      },
      {
        Reference: '4:15',
        ID: 'zkp3',
        Tags: '',
        SupportReference: '',
        Quote: 'ἐν Λαοδικίᾳ',
        Occurrence: '1',
        Note: 'a city very close to Colossae where there was also a church',
      },
      {
        Reference: '4:15',
        ID: 'wyk3',
        Tags: '',
        SupportReference: '',
        Quote: 'Νύμφαν, καὶ τὴν κατ’ οἶκον αὐτῆς ἐκκλησίαν',
        Occurrence: '1',
        Note: 'A woman named Nympha hosted a house church. Alternate translation: “Nympha and the group of believers that meets in her house”',
      },
    ],
    17: [
      {
        Reference: '4:17',
        ID: 'd39x',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-you',
        Quote:
          'εἴπατε Ἀρχίππῳ, βλέπε τὴν διακονίαν ἣν παρέλαβες ἐν Κυρίῳ, ἵνα αὐτὴν πληροῖς.',
        Occurrence: '1',
        Note: 'Paul reminds Archippus of the task God had given him and that he, Archippus, was under obligation to the Lord to fulfill it. The words “Look,” “you have received,” and “you should fulfill” all refer to Archippus and should be singular. (See: [[rc://*/ta/man/translate/figs-you]])',
      },
    ],
    18: [
      {
        Reference: '4:18',
        ID: 'an7s',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: 'Paul closes his letter with a greeting written in his own handwriting.',
      },
      {
        Reference: '4:18',
        ID: 'h3kx',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'μνημονεύετέ μου τῶν δεσμῶν',
        Occurrence: '1',
        Note: 'Paul speaks of chains when he means his imprisonment. Alternate translation: “Remember me and pray for me while I am in prison” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
      {
        Reference: '4:18',
        ID: 'w2vm',
        Tags: '',
        SupportReference: 'rc://*/ta/man/translate/figs-metonymy',
        Quote: 'ἡ χάρις μεθ’ ὑμῶν',
        Occurrence: '1',
        Note: 'Here “grace” stands for God, who shows grace or acts kindly to believers. Alternate translation: “I pray that our Lord Jesus Christ would continue to act graciously toward you all” (See: [[rc://*/ta/man/translate/figs-metonymy]])',
      },
    ],
    intro: [
      {
        Reference: '4:intro',
        ID: 'nm3y',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: '# Colossians 04 General Notes\\n## Structure and formatting\\n\\n[Colossians 4:1](../../col/04/01.md) appears to belong with the topics of Chapter 3 instead of Chapter 4.\\n\\n## Special concepts in this chapter\\n\\n### “In my own hand”\\nIt was common in the ancient Near East for the author to speak and someone else to write down the words. Many of the New Testament letters were written this way. Paul wrote the final greeting himself.\\n\\n## Other possible translation difficulties in this chapter\\n\\n### Secret truth\\n\\nPaul refers to a “secret truth” in this chapter. The role of the church in the plans of God was once unknown. But God has now revealed it. Part of this involves the Gentiles having equal standing with the Jews in the plans of God. (See: [[rc://*/tw/dict/bible/kt/reveal]])',
      },
    ],
  },
  front: {
    intro: [
      {
        Reference: 'front:intro',
        ID: 'd9hy',
        Tags: '',
        SupportReference: '',
        Quote: '',
        Occurrence: '0',
        Note: '# Introduction to Colossians\\n## Part 1: General Introduction\\n\\n### Outline of the Book of Colossians\\n\\n1. Greeting, thanksgiving, and prayer (1:1-12)\\n1. The person and work of Christ\\n- Deliverance and redemption (1:13-14)\\n- Christ: the Image of the invisible God, and the One who is over all creation (1:15-17)\\n- Christ is the Head of the Church, and the Church trusts in him (1:18-2:7)\\n1. Tests of faithfulness\\n- Warnings against false teachers (2:8-19)\\n- True godliness is not rigid rules and unbending traditions (2:20-23)\\n1. Teaching and living\\n- Life in Christ (3:1-4)\\n- Old and new life (3:5-17)\\n- Christian family (3:18-4:1)\\n1. Christian behavior (4:2-6)\\n1. Closing and greetings\\n- Paul thanks Tychicus and Onesimus (4:7-9)\\n- Paul sends greetings from his associates (4:10-14)\\n- Paul gives directions to Archippus and the Christians in Laodicea (4:15-17)\\n- Paul’s personal greeting (4:18)\\n\\n### Who wrote the Book of Colossians?\\n\\nPaul wrote the Book of Colossians. Paul was from the city of Tarsus. He had been known as Saul in his early life. Before becoming a Christian, Paul was a Pharisee. He persecuted Christians. After he became a Christian, he traveled several times throughout the Roman Empire telling people about Jesus.\\n\\nPaul wrote this letter while in prison in Rome.\\n\\n### What is the Book of Colossians about?\\n\\nPaul wrote this letter to the believers in the Asia Minor city of Colossae. The main purpose of this letter was to defend the gospel against false teachers. He did this by praising Jesus as the image of God, sustainer of all things, and head of the church. Paul wanted them to understand that only Christ is needed for God to accept them.\\n\\n### How should the title of this book be translated?\\n\\nTranslators may choose to call this book by its traditional title, “Colossians.” Or they may choose a clearer title, such as “Paul’s Letter to the Church in Colossae,” or “A Letter to the Christians in Colossae.” (See: [[rc://*/ta/man/translate/translate-names]])\\n\\n## Part 2: Important Religious and Cultural Concepts\\n\\n### What were the religious issues that the church in Colossae struggled with?\\n\\nIn the church in Colossae, there were false teachers. Their exact teaching is unknown. But they probably taught their followers to worship angels and to obey strict rules about religious ceremonies. They probably also taught that a person must be circumcised and can only eat certain types of food. Paul said these false teachings came from the minds of men and not from God.\\n\\n### How did Paul use the imagery of heaven and earth?\\n\\nIn this letter, Paul frequently spoke of heaven as “above.” He distinguished it from the earth, which Scripture speaks of as being “below.” The purpose of this imagery was to teach Christians to live in a way that honors God who lives in heaven above. Paul is not teaching that the earth or the physical world is evil. (See: [[rc://*/tw/dict/bible/kt/evil]])\\n\\n## Part 3: Important Translation Issues\\n\\n### How are the ideas of “holy” and “sanctify” represented in Colossians in the ULT?\\n\\nThe scriptures use such words to indicate any one of various ideas. For this reason, it is often difficult for translators to represent them well in their versions. In Colossians, these words usually indicate a simple reference to Christians without implying any particular role filled by them. So Colossians in the ULT uses “believers” or “those who believe in him.” (See: 1:2, 12, 26)\\n\\n### Was Jesus created or is he eternal?\\n\\nJesus was not a created being but has always existed as God. Jesus also became a human being. There is potential for confusion in Colossians 1:15 where it says Jesus “is the firstborn of all creation.” This statement means that Jesus is dominant over all of creation. It does not mean that he was the first thing God created. Translators should be careful not to imply that Jesus is a created being.\\n\\n### What does Paul mean by the expression “in Christ,” “in the Lord,” etc.?\\n\\nPaul meant to express the idea of a very close union with Christ and the believers. See the introduction to the book of Romans for more details about this kind of expression.\\n\\n### What are the major issues in the text of the Book of Colossians?\\n\\nFor the following verses, some modern versions of the Bible differ from older versions. The ULT text has the modern reading and puts the older reading in a footnote. If a translation of the Bible exists in the general region, translators should consider using the reading found in those versions. If not, translators are advised to follow the modern reading.\\n\\n* “May grace be to you, and peace from God our Father” (1:2). Some older versions have a longer reading: “Grace to you and peace from God our Father and the Lord Jesus Christ.”\\n* “Epaphras, our beloved fellow servant, who is a faithful servant of Christ on our behalf” (1:7). Some older versions read “for you”: “Epaphras, our beloved fellow servant, a faithful servant of Christ for you.”\\n* “the Father, who has made you able to have a share in the inheritance of the believers in light” (1:12). Some older versions read, “the Father, who has qualified us for a share in the inheritance in light.”\\n* “In his Son we have redemption” (1:14). Some older versions read, “In his Son we have redemption through his blood.”\\n* “and forgave us all of our trespasses” (2:13). Some older versions read: “and forgave you all of your trespasses.”\\n* “When Christ appears, who is your life” (3:4). Some older versions read, “When Christ appears, who is our life.”\\n* “It is for these things that the wrath of God is coming on the sons of disobedience” (3:6). The ULT, UST, and many other modern versions read this way. However, some modern and older versions read, “It is for these things that the wrath of God is coming.”\\n* “I sent him to you for this, that you might know the matters about us” (4:8). Some older versions read, “I sent him to you for this, that he might know the matters about you.”\\n\\n(See: [[rc://*/ta/man/translate/translate-textvariants]])',
      },
    ],
  },
}
